import { PLATFORM_ELECTRON, PLATFORM_WEB } from '../lib/runtimePlatform';

export const NAV_ITEMS = [
  {
    key: 'dashboard',
    label: 'Home',
    icon: 'dashboard',
    path: 'dashboard',
    description: 'Overview of activity, counters, and quick actions.',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'clientOnboarding',
    label: 'Clients Onboarding',
    icon: 'clientOnboarding',
    path: 'client-onboarding',
    description: 'Register companies, individuals, or dependents.',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'dailyTransactions',
    label: 'Daily Transactions',
    icon: 'dailyTransactions',
    path: 'daily-transactions',
    description: 'Daily transaction journal and quick posting workspace.',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'tasksTracking',
    label: 'Task / Tracking',
    icon: 'tasksTracking',
    path: 'tasks-tracking',
    description: 'Task assignment, ownership, and tracking board.',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'quotations',
    label: 'Quotations',
    icon: 'quotations',
    path: 'quotations',
    description: 'Offer and quotation creation before conversion.',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'proformaInvoices',
    label: 'Proforma Invoices',
    icon: 'proformaInvoices',
    path: 'proforma-invoices',
    description: 'Proforma issue, edit, and status lifecycle.',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'receivePayments',
    label: 'Receive Payments',
    icon: 'receivePayments',
    path: 'receive-payments',
    description: 'Record client payments and refunds to main balance.',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'invoiceManagement',
    label: 'Invoice Management',
    icon: 'invoiceManagement',
    path: 'invoice-management',
    description: 'Invoice lifecycle, statuses, and controls.',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'operationExpenses',
    label: 'Operation Expenses',
    icon: 'operationExpenses',
    path: 'operation-expenses',
    description: 'Operational expense recording and review.',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'portalManagement',
    label: 'Portal Management',
    icon: 'portalManagement',
    path: 'portal-management',
    description: 'Portal actions with action-level permission checks.',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'documentCalendar',
    label: 'Document Calendar',
    icon: 'documentCalendar',
    path: 'document-calendar',
    description: 'Calendar timeline for document due dates and events.',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
];

export const SEARCH_ITEMS = [
  {
    key: 'dashboard',
    label: 'Dashboard',
    description: 'Overview and activity',
    path: 'dashboard',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'settings',
    label: 'Settings',
    description: 'Brand, preferences, security',
    path: 'settings',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'appIconLibrary',
    label: 'Applications Icon Library',
    description: 'Manage tenant icon assets for apps and portals',
    path: 'settings?tab=appIconLibrary',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'clientOnboarding',
    label: 'Clients Onboarding',
    description: 'Register companies, individuals, or dependents',
    path: 'client-onboarding',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'dailyTransactions',
    label: 'Daily Transactions',
    description: 'Daily transaction journal',
    path: 'daily-transactions',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'tasksTracking',
    label: 'Task / Tracking',
    description: 'Task and tracking workspace',
    path: 'tasks-tracking',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'quotations',
    label: 'Quotations',
    description: 'Quotation workspace and conversion entrypoint',
    path: 'quotations',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'proformaInvoices',
    label: 'Proforma Invoices',
    description: 'Draft, send, and manage proforma invoices',
    path: 'proforma-invoices',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'receivePayments',
    label: 'Receive Payments',
    description: 'Collect payments or process refunds',
    path: 'receive-payments',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'invoiceManagement',
    label: 'Invoice Management',
    description: 'Invoice lifecycle controls',
    path: 'invoice-management',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'operationExpenses',
    label: 'Operation Expenses',
    description: 'Operation expenses module',
    path: 'operation-expenses',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'portalManagement',
    label: 'Portal Management',
    description: 'Portal actions with action-level permission checks',
    path: 'portal-management',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'createPortal',
    label: 'Create Portal',
    description: 'Open dedicated page to create a new portal',
    path: 'portal-management/new',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
  {
    key: 'documentCalendar',
    label: 'Document Calendar',
    description: 'Document due-date calendar view',
    path: 'document-calendar',
    platforms: [PLATFORM_WEB, PLATFORM_ELECTRON],
  },
];

export const isVisibleOnPlatform = (item, platform) => {
  if (!item?.platforms || item.platforms.length === 0) return true;
  return item.platforms.includes(platform);
};
